In [0]:
jdbcHostname = "db4free.net"
jdbcDatabase = "exocube"
jdbcPort = 3306
jdbcUrl = "jdbc:mysql://{0}:{1}/{2}?user={3}&password={4}".format(jdbcHostname, jdbcPort, jdbcDatabase, 'sample_jenish', 'Jenu7492@patel')
#x
#    a SparkDataFrame.
#url
#    JDBC database url of the form jdbc:subprotocol:subname.
#tableName
#    the name of the table in the external database.
#mode
#    one of 'append', 'overwrite', 'error', 'errorifexists', 'ignore' save mode (it is 'error' by default)
#additional JDBC database connection properties.

#'append': Contents of this SparkDataFrame are expected to be appended to existing data.
#'overwrite': Existing data is expected to be overwritten by the contents of this SparkDataFrame.
#'error' or 'errorifexists': An exception is expected to be thrown.
#'ignore': The save operation is expected to not save the contents of the SparkDataFrame and to not change the existing data.

#Insert Data
df = sqlContext.createDataFrame([(7,'vishal',2,2010,30,'M',2000)],["emp_id","name","superior_emp_id","year_joined","emp_dept_id","gender","salary"])
df.write.jdbc(jdbcUrl,"EMP",mode = 'append')
  
#select Data
pushdown_query = "(select * from employeeinfo ) emp_alias"
df = spark.read.jdbc(url=jdbcUrl, table=pushdown_query)
display(df)

id,name,department
1,Amit,RnD
2,Akash,HR
3,Sumit,ML
4,Kokan,ML
5,Yash,DS
6,Suresh,Accounts

In [0]:
import mysql.connector
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()

#CREATE table when doesn't exits
cursor.execute("CREATE table employeeinfo (id int auto_increment primary key, name varchar(255), department varchar(255))")

In [0]:
import mysql.connector
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()
#insert records
query = "insert into employeeinfo (name, department) values (%s, %s)"
#value = ("Amit", "RnD")   #insert single values
#cursor.execute(query, value)
values = [("Amit", "RnD"),("Akash", "HR"),("Sumit","ML"),("Kokan","ML"),("Yash","DS"),("Suresh","Accounts")]
cursor.executemany(query, values)  
conn.commit()

In [0]:
import mysql.connector
import pandas as pd
tblname = "employeeinfo"
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()
cursor.execute("Select * from employeeinfo")
sql_data = pd.DataFrame(cursor.fetchall())
sql_data.columns = cursor.column_names
result = sql_data.head(n=None)
display(result)

#spark_df = spark.createDataFrame(result)
#spark_df.orderBy("id").write.mode("overwrite").saveAsTable(tblname)

#pd_df = spark.sql('select * from employeeinfo').toPandas()
#display(pd_df)

id,name,department
1,Amit,RnD
2,Akash,HR
3,Sumit,ML
4,Kokan,ML
5,Yash,DS
6,Suresh,Accounts

In [0]:
import mysql.connector
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()
cursor.execute("DROP TABLE info")

In [0]:
import mysql.connector
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()
query = "update employeeinfo set name = 'Yash' where id = 5"  #update records
cursor.execute(query)
conn.commit()

In [0]:
import mysql.connector
conn = mysql.connector.connect(user='sample_jenish', password='Jenu7492@patel', host='db4free.net', database='exocube')
cursor = conn.cursor()
query = "delete from employeeinfo where id = 8"  #delete records
cursor.execute(query)
conn.commit()

In [0]:
pip install mysql-connector-python-rf